[2024-03-31T18:34:14.703+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chapter4_stocksense_bashoperator.fetch_pageviews manual__2024-03-31T18:34:13.266273+00:00 [queued]>
[2024-03-31T18:34:14.708+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chapter4_stocksense_bashoperator.fetch_pageviews manual__2024-03-31T18:34:13.266273+00:00 [queued]>
[2024-03-31T18:34:14.709+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-31T18:34:14.716+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): fetch_pageviews> on 2024-03-31 18:34:13.266273+00:00
[2024-03-31T18:34:14.719+0000] {standard_task_runner.py:60} INFO - Started process 2470 to run task
[2024-03-31T18:34:14.721+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'chapter4_stocksense_bashoperator', 'fetch_pageviews', 'manual__2024-03-31T18:34:13.266273+00:00', '--job-id', '107', '--raw', '--subdir', 'DAGS_FOLDER/pages_dag.py', '--cfg-path', '/tmp/tmp7rj2560q']
[2024-03-31T18:34:14.723+0000] {standard_task_runner.py:88} INFO - Job 107: Subtask fetch_pageviews
[2024-03-31T18:34:14.748+0000] {task_command.py:423} INFO - Running <TaskInstance: chapter4_stocksense_bashoperator.fetch_pageviews manual__2024-03-31T18:34:13.266273+00:00 [running]> on host f8f92d4c9559
[2024-03-31T18:34:14.792+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chapter4_stocksense_bashoperator' AIRFLOW_CTX_TASK_ID='fetch_pageviews' AIRFLOW_CTX_EXECUTION_DATE='2024-03-31T18:34:13.266273+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-31T18:34:13.266273+00:00'
[2024-03-31T18:34:14.794+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/pages_dag.py", line 22, in _fetch_pageviews
    with open(f"/tmp/wikipageviews", "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/wikipageviews'
[2024-03-31T18:34:14.799+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=chapter4_stocksense_bashoperator, task_id=fetch_pageviews, execution_date=20240331T183413, start_date=20240331T183414, end_date=20240331T183414
[2024-03-31T18:34:14.805+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 107 for task fetch_pageviews ([Errno 2] No such file or directory: '/tmp/wikipageviews'; 2470)
[2024-03-31T18:34:14.815+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-31T18:34:14.823+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
