[2024-04-01T12:37:33.951+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chapter4_stocksense_bashoperator.create_pet_table manual__2024-04-01T12:36:53.806346+00:00 [queued]>
[2024-04-01T12:37:33.956+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chapter4_stocksense_bashoperator.create_pet_table manual__2024-04-01T12:36:53.806346+00:00 [queued]>
[2024-04-01T12:37:33.956+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-01T12:37:33.963+0000] {taskinstance.py:2217} INFO - Executing <Task(PostgresOperator): create_pet_table> on 2024-04-01 12:36:53.806346+00:00
[2024-04-01T12:37:33.968+0000] {standard_task_runner.py:60} INFO - Started process 922 to run task
[2024-04-01T12:37:33.970+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'chapter4_stocksense_bashoperator', 'create_pet_table', 'manual__2024-04-01T12:36:53.806346+00:00', '--job-id', '152', '--raw', '--subdir', 'DAGS_FOLDER/pages_dag.py', '--cfg-path', '/tmp/tmpllhom5aa']
[2024-04-01T12:37:33.971+0000] {standard_task_runner.py:88} INFO - Job 152: Subtask create_pet_table
[2024-04-01T12:37:33.996+0000] {task_command.py:423} INFO - Running <TaskInstance: chapter4_stocksense_bashoperator.create_pet_table manual__2024-04-01T12:36:53.806346+00:00 [running]> on host d7148197e99c
[2024-04-01T12:37:34.044+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chapter4_stocksense_bashoperator' AIRFLOW_CTX_TASK_ID='create_pet_table' AIRFLOW_CTX_EXECUTION_DATE='2024-04-01T12:36:53.806346+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-01T12:36:53.806346+00:00'
[2024-04-01T12:37:34.045+0000] {sql.py:276} INFO - Executing: 
            CREATE TABLE IF NOT EXISTS pageview_counts (
 			pagename VARCHAR(50) NOT NULL,
 			pageviewcount INT NOT NULL,
				datetime TIMESTAMP NOT NULL
);
          
[2024-04-01T12:37:34.056+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 277, in execute
    hook = self.get_db_hook()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 188, in get_db_hook
    return self._hook
  File "/usr/local/lib/python3.8/functools.py", line 967, in __get__
    val = self.func(instance)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 150, in _hook
    conn = BaseHook.get_connection(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 82, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 514, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_default` isn't defined
[2024-04-01T12:37:34.059+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=chapter4_stocksense_bashoperator, task_id=create_pet_table, execution_date=20240401T123653, start_date=20240401T123733, end_date=20240401T123734
[2024-04-01T12:37:34.067+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 152 for task create_pet_table (The conn_id `postgres_default` isn't defined; 922)
[2024-04-01T12:37:34.102+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-01T12:37:34.108+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/models/baseoperator.py:1201: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2024-04-01T12:37:34.118+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
